package cz.muni.fi.anglictina.utils;

/**
 * Created by collfi on 9. 2. 2016.
 */
public class Categories {
    public static final String[] categories = {
            "adj:all",
            "adj:pert",
            "adj:ppl",
            "adv:all",
            "adverbs",
            "animals",
            "body",
            "body_care",
            "buildings",
            "business_english_nouns",
            "business_english_verbs",
            "calendar",
            "cars",
            "city",
            "clothes",
            "colors",
            "compound_words",
            "computer",
            "eating_food_drinks",
            "family",
            "frequency",
            "gardening_and_plants",
            "geographic_features",
            "health",
            "holidays",
            "house",
            "imaginary_people_and_animals",
            "jobs",
            "law",
            "math",
            "money",
            "music",
            "nationalities",
            "noun:animal",
            "noun:artifact",
            "noun:body",
            "noun:cognition",
            "noun:communication",
            "noun:event",
            "noun:feeling",
            "noun:food",
            "noun:location",
            "noun:motive",
            "noun:object",
            "noun:person",
            "noun:phenomenon",
            "noun:plant",
            "noun:possession",
            "noun:process",
            "noun:quantity",
            "noun:relation",
            "noun:shape",
            "noun:state",
            "noun:substance",
            "noun:time",
            "noun:tops",
            "noun:attribute",
            "office",
            "other",
            "other:verb",
            "parts",
            "people",
            "prepositions",
            "pronunciation",
            "punctuation_marks",
            "reading",
            "science",
            "security",
            "school",
            "smoking",
            "sports",
            "tools",
            "transportation",
            "verb:body",
            "verb:cognition",
            "verb:communication",
            "verb:competition",
            "verb:consumption",
            "verb:creation",
            "verb:emotion",
            "verb:change",
            "verb:motion",
            "verb:perception",
            "verb:possession",
            "verb:social",
            "verb:stative",
            "verb:weather",
            "weather",
            "winter",
            "words_ending_in_ful",
            "words_ending_in_less",
    };

    public static final String[] categoriesForHuman = {
            "Přídavné jméno",
            "Přídavné jméno", //adj:pert?????
            "Přídavné jméno: Lidé",
            "Příslovce",
            "Příslovce",
            "Zvířata",
            "Lidské tělo",
            "Péče o tělo",
            "Budovy",
            "Podstatné jméno: Obchod",
            "Sloveso: Obchod",
            "Kalendár",
            "Auta",
            "Město",
            "Oblečení",
            "Barvy",
            "Zložená slova",
            "Počítač",
            "Jídlo & pití",
            "Rodina",
            "Frekvence",
            "Rostliny a zahrada",
            "Zeměpisné pojmy",
            "Zdraví",
            "Svátky",
            "Dom",
            "Imaginární postavy",
            "Zaměstnání",
            "Zákon",
            "Matematika",
            "Peníze",
            "Hudba",
            "Národnosti",
            "Podstatné jméno: Zvířata",
            "Podstatné jméno: Objekty", //artifact????
            "Podstatné jméno: Lidské tělo",
            "Podstatné jméno: Poznání",
            "Podstatné jméno: Komunikace",
            "Podstatné jméno: Události",
            "Podstatné jméno: Pocity",
            "Podstatné jméno: Jídlo",
            "Podstatné jméno: Poloha",
            "Podstatné jméno: Pohyb",
            "Podstatné jméno: Objekty",
            "Podstatné jméno: Osoby",
            "Podstatné jméno: Javy",
            "Podstatné jméno: Rostliny",
            "Podstatné jméno: Vlastnictví",
            "Podstatné jméno: Procesy",
            "Podstatné jméno: Množství",
            "Podstatné jméno: Vztahy",
            "Podstatné jméno: Tvary",
            "Podstatné jméno: Stavy",
            "Podstatné jméno: Látky",
            "Podstatné jméno: Čas",
            "Podstatné jméno: Výběr", // tops???
            "Podstatné jméno: Vlastnosti",
            "Kancelář",
            "Ostatní",
            "Sloveso: Ostatní",
            "Časti",
            "Lidé",
            "Předložky",
            "Výslovnost",
            "Interpunkční znaménka",
            "Čtení",
            "Věda",
            "Zabezpečení",
            "Škola",
            "Kouření",
            "Sport",
            "Nástroje",
            "Přeprava",
            "Sloveso: Lidské tělo",
            "Sloveso: Poznání",
            "Sloveso: Komunikace",
            "Sloveso: Soutěžení",
            "Sloveso: Spotřeba",
            "Sloveso: Tvoření",
            "Sloveso: Emoce",
            "Sloveso: Změna",
            "Sloveso: Pohyb",
            "Sloveso: Vnímaní",
            "Sloveso: Vlastnictví",
            "Sloveso: Sociální",
            "Sloveso: Statické",
            "Sloveso: Počasí",
            "Počasí",
            "Zima",
            "Slova končící na -ful",
            "Slova končící na -less",
    };

    public static String toHuman(String c) {
        for (int i = 0; i < categories.length; i++) {
            if (categories[i].equals(c)) {
                return categoriesForHuman[i];
            }
        }
        return c;
    }

    public static String fromHuman(String c) {
        for (int i = 0; i < categoriesForHuman.length; i++) {
            if (categoriesForHuman[i].equals(c)) {
                return categories[i];
            }
        }
        return c;
    }
}
